-- Generated by protobuf; do not edit
local module = {}
local protobuf = require 'protobuf'

module.REQUEST = protobuf.Descriptor()
module.REQUEST_OIL_PRICES_FIELD = protobuf.FieldDescriptor()
module.REQUEST_TRANSACTIONS_FIELD = protobuf.FieldDescriptor()
module.REQUEST_HOLIDAY_FIELD = protobuf.FieldDescriptor()
module.REQUEST_OFFER_FIELD = protobuf.FieldDescriptor()
module.RESPONSE = protobuf.Descriptor()
module.RESPONSE_UNIT_SALES_FIELD = protobuf.FieldDescriptor()

module.REQUEST_OIL_PRICES_FIELD.name = 'Oil_Prices'
module.REQUEST_OIL_PRICES_FIELD.full_name = '.Request.Oil_Prices'
module.REQUEST_OIL_PRICES_FIELD.number = 1
module.REQUEST_OIL_PRICES_FIELD.index = 0
module.REQUEST_OIL_PRICES_FIELD.label = 2
module.REQUEST_OIL_PRICES_FIELD.has_default_value = false
module.REQUEST_OIL_PRICES_FIELD.default_value = 0
module.REQUEST_OIL_PRICES_FIELD.type = 5
module.REQUEST_OIL_PRICES_FIELD.cpp_type = 1

module.REQUEST_TRANSACTIONS_FIELD.name = 'Transactions'
module.REQUEST_TRANSACTIONS_FIELD.full_name = '.Request.Transactions'
module.REQUEST_TRANSACTIONS_FIELD.number = 2
module.REQUEST_TRANSACTIONS_FIELD.index = 1
module.REQUEST_TRANSACTIONS_FIELD.label = 1
module.REQUEST_TRANSACTIONS_FIELD.has_default_value = false
module.REQUEST_TRANSACTIONS_FIELD.default_value = 0
module.REQUEST_TRANSACTIONS_FIELD.type = 5
module.REQUEST_TRANSACTIONS_FIELD.cpp_type = 1

module.REQUEST_HOLIDAY_FIELD.name = 'Holiday'
module.REQUEST_HOLIDAY_FIELD.full_name = '.Request.Holiday'
module.REQUEST_HOLIDAY_FIELD.number = 3
module.REQUEST_HOLIDAY_FIELD.index = 2
module.REQUEST_HOLIDAY_FIELD.label = 2
module.REQUEST_HOLIDAY_FIELD.has_default_value = false
module.REQUEST_HOLIDAY_FIELD.default_value = 0
module.REQUEST_HOLIDAY_FIELD.type = 5
module.REQUEST_HOLIDAY_FIELD.cpp_type = 1

module.REQUEST_OFFER_FIELD.name = 'Offer'
module.REQUEST_OFFER_FIELD.full_name = '.Request.Offer'
module.REQUEST_OFFER_FIELD.number = 4
module.REQUEST_OFFER_FIELD.index = 3
module.REQUEST_OFFER_FIELD.label = 2
module.REQUEST_OFFER_FIELD.has_default_value = false
module.REQUEST_OFFER_FIELD.default_value = 0
module.REQUEST_OFFER_FIELD.type = 5
module.REQUEST_OFFER_FIELD.cpp_type = 1

module.REQUEST.name = 'Request'
module.REQUEST.full_name = '.Request'
module.REQUEST.nested_types = {}
module.REQUEST.enum_types = {}
module.REQUEST.fields = {module.REQUEST_OIL_PRICES_FIELD, module.REQUEST_TRANSACTIONS_FIELD, module.REQUEST_HOLIDAY_FIELD, module.REQUEST_OFFER_FIELD}
module.REQUEST.is_extendable = false
module.REQUEST.extensions = {}
module.RESPONSE_UNIT_SALES_FIELD.name = 'unit_sales'
module.RESPONSE_UNIT_SALES_FIELD.full_name = '.Response.unit_sales'
module.RESPONSE_UNIT_SALES_FIELD.number = 1
module.RESPONSE_UNIT_SALES_FIELD.index = 0
module.RESPONSE_UNIT_SALES_FIELD.label = 2
module.RESPONSE_UNIT_SALES_FIELD.has_default_value = false
module.RESPONSE_UNIT_SALES_FIELD.default_value = 0
module.RESPONSE_UNIT_SALES_FIELD.type = 5
module.RESPONSE_UNIT_SALES_FIELD.cpp_type = 1

module.RESPONSE.name = 'Response'
module.RESPONSE.full_name = '.Response'
module.RESPONSE.nested_types = {}
module.RESPONSE.enum_types = {}
module.RESPONSE.fields = {module.RESPONSE_UNIT_SALES_FIELD}
module.RESPONSE.is_extendable = false
module.RESPONSE.extensions = {}

module.Request = protobuf.Message(module.REQUEST)
module.Response = protobuf.Message(module.RESPONSE)


module.MESSAGE_TYPES = {'Request','Response'}
module.ENUM_TYPES = {}

return module
